Repository healthier-devs/healthier-frontend, pull requests merged in 2023-06, with the labels that each got.

#86 [Feat] 혈변 로직 구현
  src/api/diagnose/fetcher.ts
  src/data/answer_type.ts
  src/pages/diagnosis/answerButtons/index.tsx
  src/pages/diagnosis/etcButtons/index.style.tsx
  src/pages/diagnosis/etcButtons/index.tsx
  src/pages/symptomType/index.tsx
  src/utils/diagnosis.ts
Labels: Feat

#87 [Docs] 커밋 템플릿 생성
  .github/.gitmessage
Labels: Docs

#88 [Refactor] 컴포넌트 interface 선언 수정
  src/components/button/index.stories.tsx
  src/components/button/index.tsx
  src/components/contentHeader/index.stories.tsx
  src/components/contentHeader/index.tsx
  src/components/diagnosisCard/index.tsx
  src/components/dropdown/index.stories.tsx
  src/components/dropdown/index.tsx
  src/components/loading/index.tsx
  src/components/roundButton/index.stories.tsx
  src/components/roundButton/index.tsx
  src/components/tag/index.stories.tsx
  src/components/tag/index.tsx
  src/components/treatmentTag/index.stories.tsx
  src/components/treatmentTag/index.style.tsx
  src/components/treatmentTag/index.tsx
  src/interfaces/component.ts
  src/interfaces/diagnoseApi/diagnosis.ts
  src/interfaces/diagnosticResult.ts
  src/interfaces/resultPage.ts
  src/pages/diagnosisList/index.tsx
  src/pages/myDiagnosis/index.tsx
  src/pages/result/index.tsx
  src/pages/symptomType/symptomTypeComponent/index.tsx
Labels: Refactor

#92 [Feat] 예약 화면 컴포넌트 구현
  package.json
  public/images/doctorAppointment/arrow.svg
  src/components/datePicker/index.stories.tsx
  src/components/datePicker/index.style.tsx
  src/components/datePicker/index.tsx
  src/components/textField/index.stories.tsx
  src/components/textField/index.style.tsx
  src/components/textField/index.tsx
  src/utils/calendar.ts
  yarn.lock
Labels: Feat

#98 [Feat] 예상 질환 목록 UI 구현
  src/api/diagnosis.ts
  src/components/contentHeader/index.tsx
  src/components/diagnosisCard/index.stories.tsx
  src/components/diagnosisCard/index.style.tsx
  src/components/diagnosisCard/index.tsx
  src/data/severity_types.ts
  src/index.tsx
  src/interfaces/diagnosticResult.ts
  src/pages/diagnosisList/index.style.tsx
  src/pages/diagnosisList/index.tsx
  src/state/index.ts
Labels: Feat

#101 [Refactor] 정보 수집 UI 수정
  src/data/interest.ts
  src/pages/information/index.tsx
  src/pages/information/tags/index.style.tsx
  src/pages/information/tags/index.tsx
Labels: Refactor

#104 [Refactor] 공통 컴포넌트 리팩토링
  src/components/button/index.stories.tsx
  src/components/button/index.tsx
  src/components/layout/index.style.tsx
  src/components/layout/index.tsx
  src/components/tag/index.stories.tsx
  src/components/tag/index.tsx
  src/pages/diagnosis/index.style.tsx
  src/pages/diagnosis/index.tsx
  src/pages/diagnosisList/index.style.tsx
  src/pages/diagnosisList/index.tsx
  src/pages/information/index.style.tsx
  src/pages/information/index.tsx
  src/pages/main/index.style.tsx
  src/pages/main/index.tsx
  src/pages/myDiagnosis/index.style.tsx
  src/pages/myDiagnosis/index.tsx
  src/pages/symptomType/index.style.tsx
  src/pages/symptomType/index.tsx
Labels: Refactor

#106 [Feat] 개인 정보 입력 창 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/CheckIcon.tsx
  src/components/bottomSheet/index.stories.tsx
  src/components/bottomSheet/index.style.tsx
  src/components/bottomSheet/index.tsx
  src/components/textFieldStandard/index.stories.tsx
  src/components/textFieldStandard/index.style.tsx
  src/components/textFieldStandard/index.tsx
  src/data/signup_page.ts
  src/interfaces/assets.ts
  src/lib/GlobalStyle.ts
  src/pages/diagnosis/numberButtons/alcoholButton/index.tsx
  src/pages/diagnosis/numberButtons/countButton/index.tsx
  src/pages/diagnosis/numberButtons/durationButton/index.tsx
  src/pages/diagnosis/numberButtons/previousTimeButton/index.tsx
  src/pages/diagnosis/numberButtons/smockingButton/index.tsx
  src/pages/index.tsx
  src/pages/information/index.style.tsx
  src/pages/information/index.tsx
  src/pages/signUp/index.style.tsx
  src/pages/signUp/index.tsx
  src/utils/inputUtils.ts
  src/utils/inputValidator.ts
  yarn.lock
Labels: Feat
